name: sepsisfunction
namespace: sepsis-detection
runtime: python
image: quay.io/redhat_naps_da/sepsis-detection:latest
imageDigest: ""
trigger: http
builder: default
builderMap:
  default: quay.io/boson/faas-python-builder
envVars: {}
